Bootstrap: docker
From: r-base:latest

%labels
GOMAP_OWNER Wimalanathan Kokulapalan
GOMAP_MAINTAINER Wimalanathan Kokulapalan 
GOMAP_PLANT_SPECIFIC_VERSION v0.1

%environment
    export LC_ALL=C 
    export DEBIAN_FRONTEND=noninteractive
	export SCRIPT_LOC=/opt/PlantSpecific
 
%post
	export DEBIAN_FRONTEND="noninteractive"
	echo "Running post      "
	
	apt-get update && \
	apt-get install -y python3.9 git

	git clone https://github.com/bioinformapping/GOMAP-PlantSpecific.git &&
	cp -R GOMAP-PlantSpecific/PlantSpecific /opt/

	chmod 755 /opt/PlantSpecific/filterPlantSpecific.R

    #Installing the necessary R packages
	R -e 'install.packages(c("argparse","data.table","ontologyIndex","tools"), repos="https://mirror.las.iastate.edu/CRAN/", INSTALL_opts="--no-html")'

	  echo "Completed Post   "

%runscript
	/opt/PlantSpecific/filterPlantSpecific.R "$@"
