Bootstrap: docker
From: r-base:latest

%labels
GOMAP_OWNER Wimalanathan Kokulapalan
GOMAP_MAINTAINER Wimalanathan Kokulapalan 
GOMAP_VERSION v0.1

%files
	PlantSpecific /opt/

%environment
    export LC_ALL=C 
    export DEBIAN_FRONTEND=noninteractive
	export SCRIPT_LOC=/opt/PlantSpecific
 
%post
	export DEBIAN_FRONTEND="noninteractive"
	echo "Running post      "
	
	apt-get update && \
	apt-get install -y python3.9
    #Installing the necessary R packages
	R -e 'install.packages(c("argparse","data.table","ontologyIndex","parallel"), repos="https://mirror.las.iastate.edu/CRAN/", INSTALL_opts="--no-html")'
	
    #Making necessary directories
	  mkdir -p /workdir
	  mkdir -p /tmpdir
	  mkdir -p /work	  
	  mkdir -p /scratch

	  
	  echo "Completed Post   "

%startscript
	chmod 777 /tmp

%runscript
	/opt/PlantSpecific/filterPlantSpecific.R "$@"
